#!/usr/bin/env python3
"""
Remap every data center `properties.id` in public/data_centers.geojson to a new UUID,
write the updated GeoJSON, and emit a .txt file of Supabase SQL (one UPDATE block per
old→new id) for tables that store the GeoJSON id as text.

Usage (from repo root):
  python3 scripts/remap_data_center_ids.py
  python3 scripts/remap_data_center_ids.py --dry-run
  python3 scripts/remap_data_center_ids.py --geojson public/data_centers.geojson \\
      --sql-out scripts/my_migration.txt
"""

from __future__ import annotations

import argparse
import json
import uuid
from pathlib import Path


def sql_literal(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser(description="Remap data center IDs in GeoJSON + emit Supabase SQL.")
    root = Path(__file__).resolve().parent.parent
    parser.add_argument(
        "--geojson",
        type=Path,
        default=root / "public" / "data_centers.geojson",
        help="Path to data_centers.geojson (default: public/data_centers.geojson)",
    )
    parser.add_argument(
        "--sql-out",
        type=Path,
        default=root / "scripts" / "data_center_id_migration_sql.txt",
        help="Output file for SQL (default: scripts/data_center_id_migration_sql.txt)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print counts only; do not write GeoJSON or SQL file",
    )
    args = parser.parse_args()
    geo_path: Path = args.geojson

    raw = geo_path.read_text(encoding="utf-8")
    data = json.loads(raw)
    if data.get("type") != "FeatureCollection" or not isinstance(data.get("features"), list):
        raise SystemExit("Expected a GeoJSON FeatureCollection with a features array.")

    features: list[dict] = data["features"]
    # Stable old_id string → new UUID (same new id if duplicate old ids appear in file)
    old_to_new: dict[str, str] = {}

    for feat in features:
        props = feat.get("properties")
        if not isinstance(props, dict):
            continue
        old_val = props.get("id")
        old_key = "" if old_val is None else str(old_val).strip()
        if old_key not in old_to_new:
            old_to_new[old_key] = str(uuid.uuid4())
        props["id"] = old_to_new[old_key]

    # Drop empty-key mapping (no SQL for never-seen-in-DB empty string unless you had rows)
    mapping_for_sql = {k: v for k, v in old_to_new.items() if k != ""}

    lines: list[str] = [
        "-- Paste into Supabase SQL Editor. Review and backup first.",
        "-- Generated by scripts/remap_data_center_ids.py",
        "-- Updates DB rows that reference GeoJSON data center ids (TEXT).",
        "",
        "BEGIN;",
        "",
    ]

    for old_id, new_id in sorted(mapping_for_sql.items(), key=lambda kv: kv[0]):
        o, n = sql_literal(old_id), sql_literal(new_id)
        lines.append(f"-- {old_id} → {new_id}")
        lines.append(
            f"UPDATE public.data_center_confirmations SET data_center_id = {n} WHERE data_center_id = {o};"
        )
        lines.append(
            "UPDATE public.facility_tips SET facility_record_id = "
            f"{n} WHERE facility_type = 'data_center' AND facility_record_id = {o};"
        )
        lines.append(
            "UPDATE public.community_notes SET facility_record_id = "
            f"{n} WHERE facility_type = 'data_center' AND facility_record_id = {o};"
        )
        lines.append(
            "UPDATE public.facility_updates SET facility_record_id = "
            f"{n} WHERE facility_type = 'data_center' AND facility_record_id = {o};"
        )
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    sql_body = "\n".join(lines)

    print(f"Features: {len(features)}")
    print(f"Distinct old ids mapped: {len(old_to_new)} (including empty: {'' in old_to_new})")
    print(f"SQL UPDATE groups (non-empty old id): {len(mapping_for_sql)}")

    if args.dry_run:
        print("Dry run: no files written.")
        return

    args.sql_out.parent.mkdir(parents=True, exist_ok=True)
    args.sql_out.write_text(sql_body, encoding="utf-8")
    print(f"Wrote SQL: {args.sql_out}")

    out_json = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    geo_path.write_text(out_json, encoding="utf-8")
    print(f"Wrote GeoJSON: {geo_path}")


if __name__ == "__main__":
    main()
